NUMPY

In [6]:
import numpy as np

In [10]:
np.__version__

'2.1.3'

In [8]:
l1=[0,1,2,3,4,5]
l1

[0, 1, 2, 3, 4, 5]

In [9]:
type(l1)

list

#converting list into an array using numpy

In [11]:
arr=np.array(l1)
arr

array([0, 1, 2, 3, 4, 5])

In [12]:
print(type(arr))

<class 'numpy.ndarray'>


In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(10,20,4)

array([10, 14, 18])

In [18]:
np.arange(20,10)

array([], dtype=int64)

In [19]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

np.array(2,10)
2 indicates rows
10 indicates columns

In [23]:
np.array([10,10])

array([10, 10])

In [24]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
arr

array([0, 1, 2, 3, 4, 5])

#The random module has a rand() function used to create  random numbers.

In [28]:
rand(5,6)

NameError: name 'rand' is not defined

In [29]:
random.rand(5,6)

NameError: name 'random' is not defined

In [30]:
np.random.rand(5,6)

array([[0.02458185, 0.75475593, 0.87513169, 0.59976967, 0.2420933 ,
        0.72646519],
       [0.4547189 , 0.02400348, 0.76429735, 0.06197035, 0.89137183,
        0.31720429],
       [0.39295448, 0.99089697, 0.74172553, 0.53202382, 0.18622606,
        0.67948869],
       [0.26350301, 0.63506825, 0.8683771 , 0.93867474, 0.13959114,
        0.07639518],
       [0.79540646, 0.96924736, 0.05023295, 0.23444062, 0.61694867,
        0.06811202]])

In [31]:
np.random.rand(3)

array([0.24104024, 0.43020921, 0.02730565])

In [32]:
np.random.rand(5,6)

array([[0.31937485, 0.22317328, 0.78408191, 0.15561786, 0.73236073,
        0.04586872],
       [0.55271535, 0.40756964, 0.1635106 , 0.06629466, 0.58249742,
        0.96974059],
       [0.66503075, 0.01628181, 0.96043278, 0.21158563, 0.16069235,
        0.7555047 ],
       [0.37925609, 0.85976176, 0.68988797, 0.50911187, 0.8673677 ,
        0.67062135],
       [0.67389655, 0.62930821, 0.23523686, 0.42729374, 0.56629189,
        0.79555666]])

#The rand function returns float by default.
to convert them into int we use randint()

In [33]:
np.random.randint(4,6)

4

In [37]:
np.random.randint(5)

1

In [38]:
np.random.randint(1,10,2)

array([2, 6])

In [39]:
np.random.randint(0,5,5)

array([0, 3, 3, 3, 2])

In [43]:
n=np.random.randint(10,40,(5,10))
n

array([[25, 13, 21, 12, 37, 18, 14, 24, 38, 32],
       [26, 10, 25, 30, 17, 10, 33, 27, 39, 11],
       [12, 17, 25, 35, 18, 19, 25, 39, 35, 32],
       [32, 31, 14, 28, 11, 25, 19, 38, 14, 27],
       [29, 27, 13, 11, 30, 26, 28, 39, 36, 25]])

#slicing in matrices

In [44]:
n[0]

array([25, 13, 21, 12, 37, 18, 14, 24, 38, 32])

In [45]:
n[4]

array([29, 27, 13, 11, 30, 26, 28, 39, 36, 25])

In [46]:
n[0:4]

array([[25, 13, 21, 12, 37, 18, 14, 24, 38, 32],
       [26, 10, 25, 30, 17, 10, 33, 27, 39, 11],
       [12, 17, 25, 35, 18, 19, 25, 39, 35, 32],
       [32, 31, 14, 28, 11, 25, 19, 38, 14, 27]])

In [47]:
n[0:7]

array([[25, 13, 21, 12, 37, 18, 14, 24, 38, 32],
       [26, 10, 25, 30, 17, 10, 33, 27, 39, 11],
       [12, 17, 25, 35, 18, 19, 25, 39, 35, 32],
       [32, 31, 14, 28, 11, 25, 19, 38, 14, 27],
       [29, 27, 13, 11, 30, 26, 28, 39, 36, 25]])

In [48]:
n[::-1]

array([[29, 27, 13, 11, 30, 26, 28, 39, 36, 25],
       [32, 31, 14, 28, 11, 25, 19, 38, 14, 27],
       [12, 17, 25, 35, 18, 19, 25, 39, 35, 32],
       [26, 10, 25, 30, 17, 10, 33, 27, 39, 11],
       [25, 13, 21, 12, 37, 18, 14, 24, 38, 32]])

In [49]:
n

array([[25, 13, 21, 12, 37, 18, 14, 24, 38, 32],
       [26, 10, 25, 30, 17, 10, 33, 27, 39, 11],
       [12, 17, 25, 35, 18, 19, 25, 39, 35, 32],
       [32, 31, 14, 28, 11, 25, 19, 38, 14, 27],
       [29, 27, 13, 11, 30, 26, 28, 39, 36, 25]])

In [50]:
n[::2]

array([[25, 13, 21, 12, 37, 18, 14, 24, 38, 32],
       [12, 17, 25, 35, 18, 19, 25, 39, 35, 32],
       [29, 27, 13, 11, 30, 26, 28, 39, 36, 25]])

In [54]:
n

array([[25, 13, 21, 12, 37, 18, 14, 24, 38, 32],
       [26, 10, 25, 30, 17, 10, 33, 27, 39, 11],
       [12, 17, 25, 35, 18, 19, 25, 39, 35, 32],
       [32, 31, 14, 28, 11, 25, 19, 38, 14, 27],
       [29, 27, 13, 11, 30, 26, 28, 39, 36, 25]])

In [62]:
a=n[4,-3]
print(a)

39


In [60]:
a

np.int64(39)

#reshape() function is used to arrange elements into rows and columns
the number of elements and the number of rows and columns should be in accordance.

In [64]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
np.arange(1,16).reshape(4,4)

ValueError: cannot reshape array of size 15 into shape (4,4)