-- NUMPY --
1)Numpy stands for numerical python
2)it is used for performing numerical operations on numerical data
3)numpy had arrays that can be used to perform numerical operations with much ease compared to python collections.

In [1]:
#importing numpy
import numpy as np

In [7]:
#Creating arrays in python using numpy
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
#creating a multi-dimensional array
multi_array=np.array([[1,3,5,7,9],[2,4,6,8,10]])
print(multi_array)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [9]:
#creating an array of zeros
zero_array=np.zeros((2,2))
print(zero_array)

[[0. 0.]
 [0. 0.]]


In [10]:
#creating an array of ones
one_array=np.ones((2,2))
print(one_array)

[[1. 1.]
 [1. 1.]]


In [15]:
#arranging elements into an array
arr=np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [17]:
#creating an array with random numbers
#rand is function that is present in random module which is used to generate an array of the given dimensions using random numbers.
arr=np.random.rand(2,2)
print(arr)

[[0.29627378 0.30054831]
 [0.31778698 0.96900964]]


--NUMPY METHODS--

In [25]:
arr=np.array([[1,3,5,7,9],[2,4,6,8,10]])
print(arr)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [20]:
#method to know the dimensions of an array
arr.shape

(2, 5)

In [21]:
#method to know the number of elements in an array
arr.size

10

In [27]:
#method to know the data type of the elements present in an array
->even if a single element is a float and remaining all are int then the result will be a float
arr.dtype
print(arr.dtype)

int64


--PERFORMING MATHEMATICAL OPERATIONS ON ARRAY--

In [33]:
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)
print(arr1+100)
print(arr2-100)
print(arr1**2)

[ 3  7 11 15 19]
[-1 -1 -1 -1 -1]
[ 2 12 30 56 90]
[0.5        0.75       0.83333333 0.875      0.9       ]
[1 3 5 7 9]
[101 103 105 107 109]
[-98 -96 -94 -92 -90]
[ 1  9 25 49 81]


--MATRIX OPERATIONS USING NUMPY--

In [43]:
arr1=np.array([[1,3,5,7,9],[11,13,15,17,19]])
arr2=np.array([[2,4,6,8,10],[12,14,16,18,20]])
#matrix addition
print(arr1+arr2)
#matrix subtraction
print(arr1-arr2)
#element wise matrix multiplication
print(arr1*arr2)
#matrix multiplication-dot product
#print(np.dot(arr1,arr2))
#matrix division
print(arr1/arr2)

[[ 3  7 11 15 19]
 [23 27 31 35 39]]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
[[  2  12  30  56  90]
 [132 182 240 306 380]]
[[0.5        0.75       0.83333333 0.875      0.9       ]
 [0.91666667 0.92857143 0.9375     0.94444444 0.95      ]]


In [44]:
#transpose of a matrix
print(arr1.T)

[[ 1 11]
 [ 3 13]
 [ 5 15]
 [ 7 17]
 [ 9 19]]


In [57]:
arr=np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [58]:
#determinant of a matrix
determinant function is present in the linalg module of numpy
print(np.linalg.det(arr))

-2.0000000000000004


In [59]:
#inverse of a matrix
print(np.linalg.inv(arr))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [60]:
#creating an identity matrix
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [61]:
#generating eigen values and eigen vectors of a matrix using numpy
print(np.linalg.eig(arr))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [62]:
#finding the rank of a matrix
print(np.linalg.matrix_rank(arr))

2


--SOLVING LINEAR EQUATIONS USING NUMPY--

In [64]:
#if AX=B then solve for X
A=np.array([[1,2],[3,4]])
B=np.array([6,7])
X=np.linalg.solve(A,B)
print(A,B,X,sep="\n")

[[1 2]
 [3 4]]
[6 7]
[-5.   5.5]
